name: Build
on:
  push:
    branches:
      - 'exp/**' 

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/wrapper-validation-action@v6

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - run: ./gradlew build --stacktrace
